training:
    device_name: cuda:0
    train_data_files:
        - Data/twitter-2013train-A.txt
        - Data/twitter-2015train-A.txt
        - Data/twitter-2016train-A.txt
    dev_data_files:
        - Data/twitter-2013dev-A.txt
        - Data/twitter-2016dev-A.txt
    test_data_files:
        - Data/twitter-2013test-A.txt
        - Data/twitter-2015test-A.txt
        - Data/twitter-2016test-A.txt
    useExtraTrainingData: True # Use additional datasets for training which are IMDB and SST Datasets for training
    max_sequence_length: 50 
    batch_size: 128
    n_epochs: 50
    learning_rate: 0.001
    num_workers: 8
    best_model_file_path: models/DatastoriesTaskAModelBest.pth
model:
    embedding_file_path: embeddings/datastories.twitter.50d.txt
    n_lstm_layers: 2
    lstm_layer_size: 25
    dropout_propability_embeddings: 0.3
    dropout_propability_lstm: 0.5 
    bidirectional: True
    embedding_trainable: True

