training:
    device_name: cuda:0
    data_files:
        - ../../Data/twitter-2013train.txt
        - ../../Data/twitter-2015train.txt
        - ../../Data/twitter-2016train.txt
        #- ../../Data/train-dev-test/twitter-2013train-A.txt
        #- ../../Data/train-dev-test/twitter-2015train-A.txt
        #- ../../Data/train-dev-test/twitter-2016train-A.txt
        #- ../../Data/train-dev-test/twitter-2013dev-A.txt
        #- ../../Data/train-dev-test/twitter-2016dev-A.txt
        #- ../../Data/train-dev-test/twitter-2013test-A.txt
        #- ../../Data/train-dev-test/twitter-2015test-A.txt
        #- ../../Data/train-dev-test/twitter-2016test-A.txt
    max_sequence_length: 50 
    batch_size: 128
    n_epochs: 50
    test_split: 0.2
    learning_rate: 0.001
    num_workers: 8
model:
    embedding_file_path: embeddings/datastories.twitter.50d.txt
    n_lstm_layers: 2
    lstm_layer_size: 25
    dropout_propability_embeddings: 0.3
    dropout_propability_lstm: 0.5 
    bidirectional: True
    embedding_trainable: False

